learning_users/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

#Template tagging
app_name = 'basic_app'

urlpatterns = [
    url(r'^login/$', views.user_login, name = 'user_login'),
    url(r'^special/$', views.special, name = 'special'),
    url(r'^registration/$', views.registration, name = 'registration'),
]

learning_users/learning_users/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name = "index"), #this is where the homepage is at
    url(r'^basic_app/', include('basic_app.urls')),
    url(r'^logout/$', views.user_logout, name = 'logout'),
    url(r'special/', views.special, name= 'special'),
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)

    #additional
    portfolio_site = models.URLField(blank = True) #to add url

    profile_pic = models.ImageField(upload_to = 'profile_pics', blank =True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo #the class that we created

class UserForm(forms.ModelForm):
    password = forms.CharField(widget= forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserProfileInfoForm, UserForm

#for Login
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def special(required):
    return HttpResponse("Successfully logged in!")

@login_required #this will make a user that is currently logged in to logout
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username') #grabs the input from username
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)

        if user: #if there is a user
            if user.is_active: #if the user has an active account
                login(request,user)  #perform login
                return HttpResponseRedirect(reverse('index')) #send user to index
            else:
                return HttpResponse("Account Not Active") #send message
        else:
            print('Someone tried to login and failed')
            print('Username: {} and password {}' .format(username,password))
            return HttpResponse('invalid login details supplied')
    else:
        return render(request, 'basic_app/login.html')


def registration(request):

    register = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST) #Puts out username email and password from forms.py
        profile_form = UserProfileInfoForm(data=request.POST) #For the portfolio_site and profile_pic

        if user_form.is_valid() and profile_form.is_valid():
            #for user_form
            user = user_form.save() #save inputs
            user.set_password(user.password) #hashing the password
            user.save()
            #for profile_form
            profile = profile_form.save(commit=False) #dont comit to the data base yet to avoid colission
            profile.user = user #one to one

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            register = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'basic_app/registration.html', {'user_form':user_form, 'profile_form':profile_form, 'register': register})

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class = "navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class= "nav navbar-nav">
          <li><a class= "navbar-brand" href="{%url 'index'%}">Home</a></li>
          <li><a class= "navbar-link" href="{%url 'basic_app:registration'%}">Registration</a> </li>
          <li><a class="navbar-link" href="{%url 'admin:index'%}">Admin</a> </li>

          {%if user.is_authenticated%}
            <li><a class="navbar-link"  href="{%url 'logout'%}">Logout</a> </li>
            <li><a class="navbar-link" href="{%url 'basic_app:special'%}">Special</a> </li>
          {%else%}
            <li><a class="navbar-link" href="{%url 'basic_app:user_login'%}">Login</a> </li>
          {%endif%}


        </ul>
      </div>
    </nav>

    <div class="container">
      <div class="jumbotron">
        {%block body_block%}

        {%endblock%}
      </div>
    </div>
  </body>
</html>

learning_users/templates/basic_app/index.html
<!DOCTYPE html>
{%extends "basic_app/base.html"%}

{%block body_block%}
  <h1>Welcome to the homepage</h1>
  <h3>Choose the top navigation bar to jump to other pages</h3>
{%endblock%}

learning_users/templates/basic_app/login.html
<!DOCTYPE html>
{%extends "basic_app/base.html"%}

{%block body_block%}
  <h1>Please Login</h1>
  <h4>Here we will process the people with login accounts</h4>
  <form action="{%url "basic_app:user_login"%}" method="post">
    {%csrf_token%}
    <label for="username">Username:</label>
    <input type="text" name="username" value="Enter username">

    <label for="password">Password</label>
    <input type="password" name="password" value="">

    <input type="submit" name="" value="Login">
  </form>

{%endblock%}

learning_users/templates/basic_app/registration.html
<!DOCTYPE html>
{%extends 'basic_app/base.html'%}
{%load staticfiles%}

{%block body_block%}
  <h1>This is the registration page</h1>
  <h4>We will take in new users</h4>

  {%if register%}
    <h1>Thank you for registering!</h1>
  {%else%}
    <h1>Register Here!</h1>
    <h4>Fill out the form:</h4>

    <form enctype="multipart/form-data" method="post">
      {%csrf_token%}
      {{user_form.as_p}}
      {{profile_form.as_p}}
      <input type="submit" name="" value="Register">
    </form>

  {%endif%}

{%endblock%}